theme: jekyll-theme-minimal
title: Rishabh Goel(Coder-RG/coder_g)
description: A simple homepage for all my projects. This simply serves the purpose of highlighting the various cool projects I have done.
